version: '3.4'

services:
  familylawbot:
    image: familylawbot
    build:
      context: ./FamilyLawBot
      dockerfile: Dockerfile
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
